#!/usr/bin/perl

use warnings;
use strict;

use lib 'lib';

use Data::Dumper;
use Net::EPP::Simple;

use ipreg::Credentials;
use ipreg::Zones;

sub eepp {
	die "reg-push-nominet: @_: $Net::EPP::Simple::Error $Net::EPP::Simple::Message\n";
}

my $epp = Net::EPP::Simple->new(
	host	=> $creds{nominet}{host},
	user	=> $creds{nominet}{user},
	pass	=> $creds{nominet}{pass},
	stdobj	=> 1,
	stdext	=> 1,
	verify	=> 1,
	ca_path	=> '/etc/ssl/certs',
	debug   => $verbose,
);
eepp "login" unless defined $epp;

for my $z (sort keys %zone) {
	# Only Nominet zones
	next unless $zone{$z}{mzs} and $z =~ m{\.uk$} and $z !~ m{\.ac\.uk$};
	my $info = $epp->domain_info($z, undef, undef);
	eepp "domain_info $z" unless defined $info;
	print Dumper($info);
}
