#!/bin/sh
#
# For the modules we are using this is quicker and easier than faffing
# with Makefile.PL

set -e

case $# in
(2)	;;
(*)	echo 1>&2 'usage: get-perl PERLMOD VERSION'
	exit 1
esac

inst=$1
ver=$2

inst_pm=${inst%.pm}
mod=${inst_pm##*/}
idir=${inst_pm%/*}
sub=${idir##*/}

src=$sub-$mod-$ver
tgz=$src.tar.gz
url=http://www.cpan.org/modules/by-module/$sub/$tgz

w=Maketmp
mkdir -p $w

if [ ! -f $w/$tgz ]
then	curl -o $w/$tgz $url
fi
if [ ! -d $w/$src ]
then	cd $w
	echo tar xf Maketmp/$tgz
	tar xf $tgz
	cd ..
fi
if [ ! -f $inst ]
then	mkdir -p $idir
	install -v -m 0644 $w/$src/lib/$sub/$mod.pm $inst
fi
